version: '3.8'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: userDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
      - 33060


  enter-data-app:
    depends_on:
      - db
    build: ./1enter-data-app
    ports:
      - "8080:3000"
    environment:
      DB_HOST: db:3306
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: userDB

  show-results-app:
    build: ./2show-results-app
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  

volumes:
  db-data: