version: '3.8'
services:
  web-app:
    build: .
    ports:
      - "8080:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: admin
      DB_NAME: userDB

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: userDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: